inherit_from:
  - .rubocop_defaults.yml

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'test/**/*_test.rb'

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'public_suffix.gemspec'

